name: 'Terraform GitHub Actions'
on:
  - push
  - pull_request
env:
  tf_version: '1.2.8'
  tf_working_dir: '.'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout_code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: set GCP project
        id: config_project
        run: gcloud config set project pin2022

      - name: "Terraform Init"
        id: terraform_init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: '.'
          tf_actions_subcommand: init
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: "Terraform Validate"
        id: terraform_validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: '.'
          tf_actions_subcommand: validate
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: "Terraform Plan"
        id: terraform_plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: '.'
          tf_actions_subcommand: plan
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@master
        id: terraform_apply
        with:
          tf_actions_version: ${{ env.TERRAFORM_VERSION }}
          tf_actions_comment: "false"
          tf_actions_working_dir: '.'
          tf_actions_subcommand: apply
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_CREDENTIALS }}
